name: Build

on: [push, pull_request]

env:
  LC_ALL: C
  KALEIDOSCOPE_ETC_DIR: ${{ github.workspace }}/etc
  ARDUINO_DIRECTORIES_USER: ${{ github.workspace }}/.arduino/user
jobs:
  smoke-sketches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

## We delete the Bundle's version of Kaleidoscope, and symlink ourselves in.
## This makes sure we're using the current version of the library.
    - run: git clone --depth 1 --recurse-submodules=build-tools --recurse-submodules=toolchain --recurse-submodules=avr/libraries/ --jobs 16 --shallow-submodules git://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio $ARDUINO_DIRECTORIES_USER/hardware/keyboardio
    # - run: make adjust-git-timestamps
    - run: make install-arduino-cli
    - run: make configure-arduino-cli
    - run: make install-arduino-core-avr
    - run: make smoke-sketches
  run-google-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mxschmitt/action-tmate@v3
    - run: git clone --depth 1 --recurse-submodules=build-tools --recurse-submodules=toolchain --recurse-submodules=avr/libraries/ --jobs 16 --shallow-submodules git://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio $ARDUINO_DIRECTORIES_USER/hardware/keyboardio
    # - run: make adjust-git-timestamps
    - run: make install-arduino-cli
    - run: make configure-arduino-cli
    - run: make install-arduino-core-avr
    - run: make prepare-virtual
    - run: make simulator-tests
  check-astyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git clone --depth 1 --recurse-submodules=build-tools --recurse-submodules=toolchain --recurse-submodules=avr/libraries/ --jobs 16 --shallow-submodules git://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio $ARDUINO_DIRECTORIES_USER/hardware/keyboardio
    - run: make check-astyle
  check-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make shellcheck
  check-cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git clone --depth 1 --recurse-submodules=build-tools --recurse-submodules=toolchain --recurse-submodules=avr/libraries/ --jobs 16 --shallow-submodules git://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio $ARDUINO_DIRECTORIES_USER/hardware/keyboardio
    - run: make cpplint
  find-filename-conflicts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make find-filename-conflicts 
